### ISSUE TITLE
Other Model Architectures

### ISSUE THREAD

**Issue by michaelholm-ce** [jiaxiang-wu/quantized-cnn#10]
Hello -- Will you please share guidance on how to apply the quantization on other model architectures, such as Squeezenet?  Thank you in advance.

**Comment by jiaxiang-wu** [comment]
@michaelholm-ce You need to implement your own training/quantization process to convert an arbitrary pre-trained network to its quantized counterpart. The mathematics details can be found in our CVPR '16 paper. For now, I could not publish this part of code due to some issues. Sorry for that.
