### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LXWDL** [jiaxiang-wu/quantized-cnn#14]
Hello, will your home page open source code Q-CNN is also about quantifying acceleration? If I would like to ask how to use it, if you can write a description of the use I would be appreciate it,thanks.

**Comment by jiaxiang-wu** [comment]
1. What do you mean by "quantifying acceleration"?
2. The installation guideline is already provided in the README.md. You need to download images (or prepare you own), install ATLAS and OpenVML, and then compile the source code. If you need to run the original network, you still need to download the model files from the provided link.
