### ISSUE TITLE
OpenVML installation

### ISSUE THREAD

**Issue by jnjaby** [jiaxiang-wu/quantized-cnn#17]
Wondering which folder should I direct to for OpenVML installation?
When I run `make`, it return
```
mkdir -p bin
mkdir -p obj
g++ -I/usr/include/atlas -I/opt/OpenVML/include -Wall -std=c++11 -O2 -D ENABLE_ATLAS -D ENABLE_OPENVML -c src/BlasWrapper.cc -o obj/BlasWrapper.o
In file included from src/BlasWrapper.cc:8:0:
src/../include/BlasWrapper.h:84:23: fatal error: openvml.h: No such file or directory
   #include <openvml.h>
                       ^
compilation terminated.
make: *** [obj/BlasWrapper.o] Error 1

```

**Comment by jiaxiang-wu** [comment]
hi jnjaby,

You may need to modify the CXXFLAGS and LDFLAGS in the Makefile, to match your OpenVML's include and library directory.
```
CPPFLAGS=-I/usr/include/atlas -I/opt/OpenVML/include
LDFLAGS=-L/usr/lib/atlas-base -L/opt/OpenVML/lib
```
For the above configuration, /opt/OpenVML/include should contain openvml.h

**Comment by jnjaby** [comment]
It works. But still need to `export LD_LIBRARY_PATH=/Path/to/lib` for `make run`. You'd better add this to the usage in case someone may occur the same problem. Thanks!

**Comment by jiaxiang-wu** [comment]
Thanks for your suggestion. README.md updated in 3bec22e5bb77a80edb1b7180d12b409497d50891.
