### ISSUE TITLE
https://github.com/jiaxiang-wu/caffe-QCNN 

### ISSUE THREAD

**Issue by KangolHsu** [jiaxiang-wu/quantized-cnn#19]
https://github.com/jiaxiang-wu/caffe-QCNN
You github above did not contain the quantized convolution layer ？

**Comment by jiaxiang-wu** [comment]
Hi @KangolHsu 
That repository is deprecated, and does not contain the quantized convolutional layer. Sorry for causing your confusion.

**Comment by KangolHsu** [comment]
thank you。got it @jiaxiang-wu
