### ISSUE TITLE
the onedrive file not exist( ILSVRC12.227x227.IMG and AlexNet/Bin.Files )

### ISSUE THREAD

**Issue by ChenKexiong** [jiaxiang-wu/quantized-cnn#20]
I tried the links [ILSVRC12.227x227.IMG](https://onedrive.live.com/redir?resid=D968C5EC99B231C!647138&authkey=!AFq00tB5N71t1Cw&ithint=file%2cbin) [AlexNet/Bin.Files](https://onedrive.live.com/redir?resid=D968C5EC99B231C!742681&authkey=!AMiIg1D39Bdxumo&ithint=file%2cgzl) from README.md, but the corresponding file did not exist

**Comment by jiaxiang-wu** [comment]
Hi @ChenKexiong 

The previous links are deprecated, and updated links are provided in 4d020e17026df90e40111d219e3eb74e0afb1588.
Sorry for your trouble.

**Comment by ChenKexiong** [comment]
Thanks a lot!!!
It's running OK eventually~~
