### ISSUE TITLE
question about your paper

### ISSUE THREAD

**Issue by sxsxsx** [jiaxiang-wu/quantized-cnn#22]
hello,thank you for your contribution to the model quantification model
but I have some problems when I read your paper,
when you quantification the conv kernel and FC,what do you mean by pre-computation?
I can not understand it,the input can not be sure during the test phase ,how to realize the pre-computation

**Comment by jiaxiang-wu** [comment]
Hi there,
The pre-computation is carried out during the test phase, depending on the actual input and pre-quantized conv./fc. kernels. The test phase computation involves two parts:
* pre-computation of look-up tables of inner products
* response computation based on look-up tables of inner products

Here, "pre-computation" indicates that look-up tables are computed prior to their actual usage in the response computation. The overall computation complexity of these two parts is still smaller than the direct computation of layer responses, for both convolutional and fully-connected layers.
