### ISSUE TITLE
question about pre-computed LUT

### ISSUE THREAD

**Issue by hiyijian** [jiaxiang-wu/quantized-cnn#5]
hi @jiaxiang-wu ,
  You teach us to quantize fully-connected layer weights via codebooks. But There is not any instruction in the paper for how the input S(m) could be quantized, So I am not every clear that how the LUT could be pre-computed. Would you pls to explain this more?

**Comment by jiaxiang-wu** [comment]
Dear @hiyijian ,

We do not quantize the input S(m). Instead, for a new-coming input S, we compute its corresponding look-up table (LUT) in the run-time and then use it for the approximate layer response computation. Please refer to Line 806-818 and 993-999 for the LUT computation in the convolutional and fully-connected layers, respectively.

Best,

**Comment by hiyijian** [comment]
Cool. Thank you.
