### ISSUE TITLE
Program crashed right before ends: Double release buffer in ~CaffeEva::~CaffeEva(void) 

### ISSUE THREAD

**Issue by hiyijian** [jiaxiang-wu/quantized-cnn#7]
In CaffeEva::~CaffeEva(void) , I think it is inappropriate that calling ~Matrix() manually. It causes double release problem due to matrix allocated in stack will be released automatically.
This should be enough ^_^:
CaffeEva::~CaffeEva(void) {
 // release dynamically allocated memory
 delete [] featMapLst;
 for (int layerInd = 0; layerInd < caffeParaObj.layerCnt; layerInd++) {
   FeatBufStrLst& featBufStrLst = featBufStrMat[layerInd];
   for (std::size_t bufInd = 0; bufInd < featBufStrLst.size(); bufInd++) {
     if (featBufStrLst[bufInd].pFeatBuf != nullptr) {
       delete featBufStrLst[bufInd].pFeatBuf;
     }  // ENDIF: featBufStrLst
   }  // ENDFOR: bufInd
 }  // ENDFOR: layerInd

 // destory objects: <caffeParaObj>
}

**Comment by jiaxiang-wu** [comment]
Thanks for your advice. This bug is now fixed in the commit [_012e13d_](https://github.com/jiaxiang-wu/quantized-cnn/commit/012e13d38043aedfbcbfbf3e0e7ac3bc4d8e4a10).
